#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# FundTrail — native one-click launcher & stopper  (Mac / Linux)  — NO DOCKER.
#
#   ./fundtrail.sh                 → start (default)
#   ./fundtrail.sh start           → start the server
#   ./fundtrail.sh stop            → stop  the server
#   ./fundtrail.sh reset-password  → regenerate admin/officer login (data kept)
#
# Runs the Flask app directly in a Python 3.11 virtualenv. The app requires
# Python 3.11 (pandas / Flask-SQLAlchemy pin >=3.11); this script finds it,
# builds the venv once, installs requirements once, and launches the server.
# Case data persists in the app's per-user data dir (unchanged across restarts).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
MAIN_DIR="$REPO_DIR/main"
VENV_DIR="$MAIN_DIR/.venv311"
ENV_FILE="$REPO_DIR/.env"
PID_FILE="$REPO_DIR/.fundtrail.pid"
LOG_FILE="$REPO_DIR/.fundtrail.log"
PORT="${PORT:-5050}"
BORDER="+----------------------------------------------------------+"

# ── Find a Python 3.11+ interpreter ──────────────────────────────────────────
find_python() {
    local cand
    for cand in python3.13 python3.12 python3.11 python3 python; do
        if command -v "$cand" &>/dev/null && "$cand" - <<'PY' &>/dev/null
import sys; sys.exit(0 if sys.version_info[:2] >= (3, 11) else 1)
PY
        then
            command -v "$cand"; return 0
        fi
    done
    return 1
}

# ── STOP ─────────────────────────────────────────────────────────────────────
do_stop() {
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        kill "$(cat "$PID_FILE")" 2>/dev/null || true
        rm -f "$PID_FILE"
        echo "$BORDER"
        echo "|  FundTrail has stopped.                                  |"
        echo "|  Your case data is safe — run ./fundtrail.sh to restart. |"
        echo "$BORDER"
    else
        # Fall back to a port-based kill if the pidfile is stale.
        local pids; pids=$(lsof -ti tcp:"$PORT" 2>/dev/null || true)
        if [[ -n "$pids" ]]; then
            echo "$pids" | xargs kill 2>/dev/null || true
            echo "Stopped FundTrail (port $PORT)."
        else
            echo "FundTrail is not running — nothing to stop."
        fi
        rm -f "$PID_FILE"
    fi
}

# ── START ────────────────────────────────────────────────────────────────────
do_start() {
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "FundTrail is already running (PID $(cat "$PID_FILE"))."
        echo "  Open http://127.0.0.1:$PORT  — or ./fundtrail.sh stop first."
        exit 0
    fi

    # Step 1 — locate Python 3.11+
    local py
    if ! py=$(find_python); then
        echo "ERROR: Python 3.11+ is required but was not found." >&2
        echo "  Install it, then re-run:" >&2
        echo "    macOS:  brew install python@3.11" >&2
        echo "    Linux:  sudo apt-get install -y python3.11 python3.11-venv  (or your distro's pkg)" >&2
        exit 1
    fi
    echo "Using $($py --version) at $py"

    # Step 2 — create the venv once
    if [[ ! -x "$VENV_DIR/bin/python" ]]; then
        echo "Creating virtualenv at $VENV_DIR ..."
        "$py" -m venv "$VENV_DIR"
    fi
    local vpy="$VENV_DIR/bin/python"

    # Step 3 — install requirements once (or when flask is missing)
    if ! "$vpy" -c "import flask, pandas, dotenv, openpyxl, xlrd" &>/dev/null; then
        echo "Installing dependencies (first run, this can take a few minutes)..."
        "$vpy" -m pip install --upgrade pip >/dev/null
        "$vpy" -m pip install -r "$MAIN_DIR/requirements.txt"
    fi

    # Step 4 — generate .env with a fresh SECRET_KEY on first run
    if [[ ! -f "$ENV_FILE" ]] || ! grep -q "^SECRET_KEY=" "$ENV_FILE" 2>/dev/null; then
        echo "First run — generating .env ..."
        local key; key=$("$vpy" -c "import secrets; print(secrets.token_hex(32))")
        cat >> "$ENV_FILE" <<ENVEOF
# Auto-generated by fundtrail.sh — keep this file private, never commit it.
SECRET_KEY=$key
# Allows plain-HTTP session cookies on a local LAN (no HTTPS proxy).
SESSION_COOKIE_INSECURE=true
PASSWORD_MAX_AGE_DAYS=90
ENVEOF
        echo "  .env created with a fresh SECRET_KEY."
    fi

    # Step 5 — launch the Flask app in the background
    echo "Starting FundTrail..."
    ( cd "$MAIN_DIR" && PORT="$PORT" nohup "$vpy" app.py >"$LOG_FILE" 2>&1 & echo $! >"$PID_FILE" )

    # Step 6 — wait until the server answers
    echo -n "Waiting for the app to be ready"
    for _ in $(seq 1 40); do
        if "$vpy" - "$PORT" <<'PY' &>/dev/null
import sys, urllib.request
url = f"http://127.0.0.1:{sys.argv[1]}/login"
try:
    urllib.request.urlopen(url, timeout=2); sys.exit(0)
except Exception:
    sys.exit(1)
PY
        then echo " ready!"; break; fi
        if ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
            echo ""; echo "ERROR: the app exited during startup. Last log lines:" >&2
            tail -n 20 "$LOG_FILE" >&2; rm -f "$PID_FILE"; exit 1
        fi
        echo -n "."; sleep 1
    done
    echo ""

    # Step 7 — print access URLs
    local lan_ip=""
    lan_ip=$(ipconfig getifaddr en0 2>/dev/null) || true
    [[ -z "$lan_ip" ]] && lan_ip=$(ipconfig getifaddr en1 2>/dev/null) || true
    [[ -z "$lan_ip" ]] && lan_ip=$(ip route get 1 2>/dev/null \
        | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1); exit}') || true
    [[ -z "$lan_ip" ]] && lan_ip="<your-machine-ip>"

    echo "$BORDER"
    echo "|  FundTrail is running                                    |"
    printf "|  Local:   http://127.0.0.1:%-29s|\n" "$PORT"
    printf "|  LAN:     http://%-39s|\n" "$lan_ip:$PORT"
    echo "|  Share the LAN address with officers on the same Wi-Fi.  |"
    echo "$BORDER"
    echo ""
    echo "First-login credentials are printed once in the app log / data dir:"
    echo "  ~/.local/share/FundTrail/INITIAL_CREDENTIALS.txt"
    echo "Logs:     $LOG_FILE"
    echo "To stop:  ./fundtrail.sh stop"
}

# ── RESET PASSWORD (data preserved) ──────────────────────────────────────────
do_reset_password() {
    local vpy="$VENV_DIR/bin/python"
    if [[ ! -x "$vpy" ]]; then
        echo "Run ./fundtrail.sh once first to set up the environment." >&2; exit 1
    fi
    echo "Resetting admin & officer passwords (case data is NOT affected)..."
    ( cd "$MAIN_DIR" && "$vpy" scripts/create_user.py )
}

case "${1:-start}" in
    start) do_start ;;
    stop)  do_stop  ;;
    reset-password|reset) do_reset_password ;;
    *)
        echo "Usage: ./fundtrail.sh [start|stop|reset-password]"
        echo "  start           — (default) set up venv and launch the server natively"
        echo "  stop            — stop the server (case data is preserved)"
        echo "  reset-password  — regenerate the admin/officer login (data preserved)"
        exit 1 ;;
esac
