sonar.projectKey=harishvidyarth_CyberCrime
sonar.organization=harishvidyarth
sonar.sources=main/
sonar.exclusions=**/migrations/**,**/tests/**,**/static/**,**/templates/**
sonar.tests=main/tests/
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
