"""add missing columns

Revision ID: 639e2a9d0ff7
Revises: f3640f68c53f
Create Date: 2025-10-28 12:32:32.575691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639e2a9d0ff7'
down_revision = 'f3640f68c53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_column('transaction_count')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
