"""Add failed_login_attempts

Revision ID: a0b56cf382d7
Revises: 511b73d5b1d3
Create Date: 2026-01-22 00:54:23.536608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0b56cf382d7'
down_revision = '511b73d5b1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('complaint_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('complaint_ibfk_2'), 'user', ['assigned_to'], ['id'])

    # ### end Alembic commands ###
