#!/usr/bin/env python3
"""
One-command setup / login reset for FundTrail.

Run this right after cloning the repo, or any time you're locked out:

    cd main
    python scripts/create_user.py

What it does:
  1. Creates a .env file with a fresh random SECRET_KEY (only if one does not
     already exist — your existing .env is never overwritten). Without this the
     app refuses to start, which is why a fresh clone "did nothing".
  2. Creates the database tables if they are missing.
  3. Creates OR resets the 'admin' and 'officer' accounts with fresh, strong,
     random passwords and forces a password change on first login.
  4. Prints the passwords AND saves them to data/INITIAL_CREDENTIALS.txt
     (which is gitignored) so the admin password can never get "lost" again.

Why the old version didn't work:
  - It was run from the scripts/ folder, so `from app import app` couldn't find
    app.py (it lives one level up, in main/).
  - Importing app.py auto-creates the users with random passwords first, so the
    old `if not User.query...` checks always skipped and the intended password was
    never set. This version RESETS the accounts, so it always lands in a known state.
"""

import os
import sys
import secrets
import string
import contextlib

# --- Make `import app` / `import models` work no matter where this is run from ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MAIN_DIR = os.path.dirname(SCRIPT_DIR)  # .../main
if MAIN_DIR not in sys.path:
    sys.path.insert(0, MAIN_DIR)

ENV_PATH = os.path.join(MAIN_DIR, ".env")
SPECIALS = '!@#$%^&*(),.?":{}|<>'


def ensure_env():
    """Create a working .env with a fresh secret key if it doesn't exist yet."""
    if os.path.exists(ENV_PATH):
        print("[setup] .env already exists — leaving it untouched.")
        return
    secret = secrets.token_hex(32)
    with open(ENV_PATH, "w") as f:
        f.write(
            "# Auto-generated by scripts/create_user.py — safe to edit.\n"
            f"SECRET_KEY={secret}\n"
            "\n"
            "# Allow login over local http (offline / desktop use). This MUST be true\n"
            "# for the app to work without HTTPS, otherwise the browser drops the\n"
            "# session cookie and you get CSRF 'Bad request' errors. Set it to false\n"
            "# only when you deploy behind real HTTPS.\n"
            "SESSION_COOKIE_INSECURE=true\n"
            "\n"
            "FLASK_DEBUG=false\n"
            "PORT=5050\n"
        )
    try:
        os.chmod(ENV_PATH, 0o600)
    except Exception:
        pass
    print(f"[setup] Created {ENV_PATH} with a fresh random SECRET_KEY.")


def strong_password(length=16):
    alphabet = string.ascii_letters + string.digits + SPECIALS
    while True:
        pw = "".join(secrets.choice(alphabet) for _ in range(length))
        if (
            any(c.islower() for c in pw)
            and any(c.isupper() for c in pw)
            and any(c.isdigit() for c in pw)
            and any(c in SPECIALS for c in pw)
        ):
            return pw


def main():
    ensure_env()

    # Import only AFTER .env exists — importing app.py reads SECRET_KEY from it.
    # Importing also runs app.py's own first-run seeder, which prints its own
    # passwords. We reset the accounts right after, so silence that import-time
    # output to avoid showing two confusing sets of passwords.
    with contextlib.redirect_stdout(open(os.devnull, "w")):
        from app import app, secure_base
        from models import db, User

    accounts = [("admin", "Admin"), ("officer", "Investigative Officer")]
    results = []

    with app.app_context():
        db.create_all()

        for username, role in accounts:
            # Use the SAME known default as the app's first-run seed so every
            # reset / clone gives a consistent login (forced change on first login).
            # Override with SEED_ADMIN_PASSWORD / SEED_OFFICER_PASSWORD if desired.
            if username == "admin":
                pw = os.environ.get("SEED_ADMIN_PASSWORD", "Admin@123456")
            else:
                pw = os.environ.get("SEED_OFFICER_PASSWORD", "Officer@123456")
            user = User.query.filter_by(username=username).first()
            if user is None:
                user = User(username=username, role=role)
                db.session.add(user)
                action = "created"
            else:
                user.role = role
                action = "reset"
            user.set_password(pw)
            user.must_change_password = True  # force change on first login
            user.failed_login_attempts = 0  # clear any lockout
            user.account_locked_until = None
            results.append((username, role, pw, action))

        db.session.commit()

        # Build the credentials text, save it, and print it.
        lines = [
            "FundTrail login credentials (auto-generated)",
            "Change them on first login, then delete this file.",
            "",
        ]
        for username, role, pw, action in results:
            lines.append(f"  {username:<8} ({action:<7}) [{role}]  password: {pw}")
        body = "\n".join(lines) + "\n"

        saved_to = None
        try:
            creds_path = os.path.join(secure_base, "INITIAL_CREDENTIALS.txt")
            with open(creds_path, "w") as cf:
                cf.write(body)
            try:
                os.chmod(creds_path, 0o600)
            except Exception:
                pass
            saved_to = creds_path
        except Exception as exc:
            print(f"[setup] Could not save credentials file: {exc}")

    print("\n" + "=" * 60)
    print(body.rstrip())
    print("=" * 60)
    if saved_to:
        print(f"Saved to: {saved_to}")
    print("Next:  python app.py    then open  http://127.0.0.1:5050\n")


if __name__ == "__main__":
    main()
