# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('Template for letter generation_suspect accounts.docx', '.'),
        ('Template for letter generation_victim account.docx', '.'),
        ('IFSC_CODES.xlsx', '.'),
        ('IFSC_CODES.json', '.'),
        ('IFSC_CODES.pkl', '.'),
        ('ATM.txt', '.'),
        ('.env', '.')
    ],
    hiddenimports=[
        'flask_sqlalchemy',
        'flask_login',
        'flask_migrate',
        'pymysql',
        'cryptography',
        'openpyxl',
        'requests',
        'python-dotenv',
        'flask_wtf',
        'flask_limiter',
        'xhtml2pdf',
        'reportlab.graphics.barcode',
        'reportlab.graphics.barcode.code128',
        'reportlab.graphics.barcode.code39',
        'reportlab.graphics.barcode.code93',
        'reportlab.graphics.barcode.common',
        'reportlab.graphics.barcode.widgets',
        'reportlab.graphics.barcode.eanbc',
        'reportlab.graphics.barcode.usps',
        'reportlab.graphics.barcode.usps4s',
        'reportlab.graphics.barcode.qr',
        'reportlab.graphics.barcode.qrencoder',
        'reportlab.graphics.barcode.dmtx',
        'reportlab.graphics.barcode.ecc200datamatrix',
        'reportlab.graphics.barcode.fourstate',
        'reportlab.graphics.barcode.lto',
        'docx',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FundTrailTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
